### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by paolorevillosa** [JantHsueh/upload-file-action#3]
I was trying to upload artifacts from my git repository to a specific server, but i was stuck on this error

`Run JantHsueh/upload-file-action@master
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at jsonToMap (/home/runner/work/_actions/JantHsueh/upload-file-action/master/dist/index.js:2313:27)
    at main (/home/runner/work/_actions/JantHsueh/upload-file-action/master/dist/index.js:2267:22)
    at Object.378 (/home/runner/work/_actions/JantHsueh/upload-file-action/master/dist/index.js:2317:1)
    at __webpack_require__ (/home/runner/work/_actions/JantHsueh/upload-file-action/master/dist/index.js:22:30)
    at startup (/home/runner/work/_actions/JantHsueh/upload-file-action/master/dist/index.js:37:19)
    at /home/runner/work/_actions/JantHsueh/upload-file-action/master/dist/index.js:41:18
    at Object.<anonymous> (/home/runner/work/_actions/JantHsueh/upload-file-action/master/dist/index.js:44:10)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
Error: Unexpected end of JSON input`

Here is my yml script
`- name: Upload File
        id: upload
        uses: JantHsueh/upload-file-action@master
        with:
          url: _my url_
          fileForms: '{"apk_file":"${{steps.sign_app.outputs.signedReleaseFile}}"}'`

i even tried your example (i just removed fileForms and change the url) but still give the same error

![upload_file_action](https://user-images.githubusercontent.com/29852199/104889430-321c6980-59a9-11eb-8a5e-331c88902be8.png)

**Comment by MichaelVoelkel** [comment]
Also encountered it, just pass in an empty JSON for fileForms, it's not really optional it may just be empty
